/*
 * TVP/2007 — channel lineup.
 * GENERATED by tvp/tools/curate.mjs on 2026-07-13 — edit that script, not this file.
 * 12 channels · 114 programs · 71.3 hours of free/open video,
 * all verified range-streamable from the Internet Archive at harvest time.
 * Hand-picked programs carry license notes; harvested items are from
 * archive.org public collections (Prelinger, Film Noir, SciFi_Horror, …).
 */

const CHANNELS = [
 {
  num: 1,
  id: "animation-station",
  name: "Animation Station",
  category: "Cartoons & Animation",
  tagline: "Round-the-clock open-source toons",
  art: "https://archive.org/services/img/BigBuckBunny_124",
  programs: [
   {
    title: "Big Buck Bunny",
    year: 2008,
    dur: 596.5,
    src: "https://archive.org/download/BigBuckBunny_124/Content/big_buck_bunny_720p_surround.mp4",
    desc: "A giant rabbit takes gentle revenge on three bullying rodents.",
    license: "CC-BY · Blender Foundation",
    art: "https://archive.org/services/img/BigBuckBunny_124"
   },
   {
    title: "Caminandes: Gran Dillama",
    year: 2013,
    dur: 146,
    src: "https://archive.org/download/Caminandes2GranDillama/02_gran_dillama_1080p.mp4",
    desc: "The grass really is greener on the other side of the road.",
    license: "CC-BY · Blender Foundation",
    art: "https://archive.org/services/img/Caminandes2GranDillama"
   },
   {
    title: "Caminandes: Llama Drama",
    year: 2013,
    dur: 90,
    src: "https://archive.org/download/Caminandes1LlamaDrama/01_llama_drama_1080p.mp4",
    desc: "Koro the llama versus a very inconvenient fence.",
    license: "CC-BY · Blender Foundation",
    art: "https://archive.org/services/img/Caminandes1LlamaDrama"
   }
  ]
 },
 {
  num: 2,
  id: "open-cinema",
  name: "Open Cinema",
  category: "Film",
  tagline: "The Blender open movie channel",
  art: "https://archive.org/services/img/Sintel",
  programs: [
   {
    title: "Elephants Dream",
    year: 2006,
    dur: 653.8,
    src: "https://archive.org/download/ElephantsDream/ed_1024_512kb.mp4",
    desc: "Two strange characters explore an infinite machine.",
    license: "CC-BY · Blender Foundation",
    art: "https://archive.org/services/img/ElephantsDream"
   },
   {
    title: "Sintel",
    year: 2010,
    dur: 888,
    src: "https://archive.org/download/Sintel/sintel-2048-stereo_512kb.mp4",
    desc: "A lone girl searches for the dragon she once rescued.",
    license: "CC-BY · Blender Foundation",
    art: "https://archive.org/services/img/Sintel"
   },
   {
    title: "Tears of Steel",
    year: 2012,
    dur: 734.1,
    src: "https://archive.org/download/Tears-of-Steel/tears_of_steel_720p.mp4",
    desc: "Scientists restage an old heartbreak to save Amsterdam from robots.",
    license: "CC-BY · Blender Foundation",
    art: "https://archive.org/services/img/Tears-of-Steel"
   },
   {
    title: "Cosmos Laundromat: First Cycle",
    year: 2015,
    dur: 730.6,
    src: "https://archive.org/download/CosmosLaundromatFirstCycle/Cosmos%20Laundromat%20-%20First%20Cycle%20%281080p%29.mp4",
    desc: "A suicidal sheep is offered any life he wants.",
    license: "CC-BY · Blender Foundation",
    art: "https://archive.org/services/img/CosmosLaundromatFirstCycle"
   },
   {
    title: "Spring",
    year: 2019,
    dur: 464.2,
    src: "https://archive.org/download/springopenmovie/springopenmovie.mp4",
    desc: "A shepherd girl and her dog face ancient spirits.",
    license: "CC-BY · Blender Foundation",
    art: "https://archive.org/services/img/springopenmovie"
   }
  ]
 },
 {
  num: 3,
  id: "cartoon-classics",
  name: "Cartoon Classics",
  category: "Kids",
  tagline: "Hand-drawn wonders since 1911",
  art: "https://archive.org/services/img/Gertie",
  programs: [
   {
    title: "Little Nemo",
    year: 1911,
    dur: 634.2,
    src: "https://archive.org/download/LittleNemo_548/LittleNemo_512kb.mp4",
    desc: "Winsor McCay's pioneering hand-tinted animation.",
    license: "Public domain",
    art: "https://archive.org/services/img/LittleNemo_548"
   },
   {
    title: "Gertie the Dinosaur",
    year: 1914,
    dur: 738.6,
    src: "https://archive.org/download/Gertie/GertietheDinosaur.mp4",
    desc: "The first cartoon star ever.",
    license: "Public domain",
    art: "https://archive.org/services/img/Gertie"
   },
   {
    title: "Steamboat Willie",
    year: 1928,
    dur: 442.4,
    src: "https://archive.org/download/SteamboatWillie/Steamboat%20Willie.mp4",
    desc: "The synchronized-sound sensation that launched a mouse.",
    license: "Public domain",
    art: "https://archive.org/services/img/SteamboatWillie"
   },
   {
    title: "Flip The Frog - Fiddlesticks",
    year: 1930,
    dur: 372.5,
    src: "https://archive.org/download/FLIP_FROG-FIDDLESTICKS/FLIP_FROG-FIDDLESTICKS_64k_512kb.mp4",
    art: "https://archive.org/services/img/FLIP_FROG-FIDDLESTICKS",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Betty Boop: Snow White",
    year: 1933,
    dur: 424.1,
    src: "https://archive.org/download/bb_snow_white/bb_snow_white_512kb.mp4",
    art: "https://archive.org/services/img/bb_snow_white",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Superman: The Mechanical Monsters",
    year: 1941,
    dur: 613.8,
    src: "https://archive.org/download/SupermanTheMechanicalMonsters1941/Superman%20-%20The%20Mechanical%20Monsters%20%281941%29.mp4",
    desc: "Fleischer's art-deco Superman battles robot bank-robbers.",
    license: "Public domain",
    art: "https://archive.org/services/img/SupermanTheMechanicalMonsters1941"
   },
   {
    title: "Woody Woodpecker in Pantry Panic",
    year: 1941,
    dur: 411.5,
    src: "https://archive.org/download/woody_woodpecker_pantry_panic/woody_woodpecker_pantry_panic_512kb.mp4",
    art: "https://archive.org/services/img/woody_woodpecker_pantry_panic",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Shuteye Popeye",
    year: 1952,
    dur: 382.1,
    src: "https://archive.org/download/popeye_shuteye_popeye/popeye_shuteye_popeye_512kb.mp4",
    art: "https://archive.org/services/img/popeye_shuteye_popeye",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Popeye: Taxi-Turvy",
    year: 1954,
    dur: 363,
    src: "https://archive.org/download/popeye_taxi-turvey/popeye_taxi-turvey_512kb.mp4",
    art: "https://archive.org/services/img/popeye_taxi-turvey",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Private Eye Popeye",
    year: 1954,
    dur: 392.6,
    src: "https://archive.org/download/popeye_private_eye_popeye/popeye_private_eye_popeye_512kb.mp4",
    art: "https://archive.org/services/img/popeye_private_eye_popeye",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Popeye: I Don't Scare",
    year: 1956,
    dur: 366.5,
    src: "https://archive.org/download/popeye_i_dont_scare/popeye_i_dont_scare_512kb.mp4",
    art: "https://archive.org/services/img/popeye_i_dont_scare",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Patriotic Popeye",
    year: 1957,
    dur: 363.2,
    src: "https://archive.org/download/popeye_patriotic_popeye/popeye_patriotic_popeye_512kb.mp4",
    art: "https://archive.org/services/img/popeye_patriotic_popeye",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Betty Boop Cartoons",
    dur: 335.1,
    src: "https://archive.org/download/BettyBoopCartoons/Betty_Boop_More_Pep_1936_512kb.mp4",
    art: "https://archive.org/services/img/BettyBoopCartoons",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "The Big Bad Wolf",
    dur: 498.6,
    src: "https://archive.org/download/the_big_bad_wolf/the_big_bad_wolf_512kb.mp4",
    art: "https://archive.org/services/img/the_big_bad_wolf",
    desc: "",
    license: "via archive.org"
   }
  ]
 },
 {
  num: 4,
  id: "creature-feature",
  name: "Creature Feature",
  category: "Cult",
  tagline: "Late-night chills, all night",
  art: "https://archive.org/services/img/Night.Of.The.Living.Dead_1080p",
  programs: [
   {
    title: "Nosferatu, eine Symphonie des Grauens (A Symphony of Horror)",
    year: 1922,
    dur: 5601.8,
    src: "https://archive.org/download/Nosferatu_most_complete_version_93_mins./Nosferatu_1922_Symphony_of_Horror_512kb.mp4",
    art: "https://archive.org/services/img/Nosferatu_most_complete_version_93_mins.",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "White Zombie",
    year: 1932,
    dur: 3919.8,
    src: "https://archive.org/download/white_zombie/white_zombie_512kb.mp4",
    srcHi: "https://archive.org/download/white_zombie/white_zombie.mp4",
    art: "https://archive.org/services/img/white_zombie",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "The Ghost Train",
    year: 1941,
    dur: 4882.3,
    src: "https://archive.org/download/TheGhostTrain/TheGhostTrain_512kb.mp4",
    srcHi: "https://archive.org/download/TheGhostTrain/TheGhostTrain.mp4",
    art: "https://archive.org/services/img/TheGhostTrain",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "House on Haunted Hill",
    year: 1959,
    dur: 4483.2,
    src: "https://archive.org/download/house_on_haunted_hill_ipod/house_on_haunted_hill_512kb.mp4",
    desc: "Vincent Price offers five guests $10,000 to survive the night.",
    license: "Public domain",
    art: "https://archive.org/services/img/house_on_haunted_hill_ipod"
   },
   {
    title: "City of the Dead/Horror Hotel",
    year: 1960,
    dur: 4554,
    src: "https://archive.org/download/Horror_Hotel/Horror_Hotel_512kb.mp4",
    srcHi: "https://archive.org/download/Horror_Hotel/Horror_Hotel.mp4",
    art: "https://archive.org/services/img/Horror_Hotel",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Carnival of Souls",
    year: 1962,
    dur: 4979.6,
    src: "https://archive.org/download/CarnivalofSouls/CarnivalOfSouls_512kb.mp4",
    srcHi: "https://archive.org/download/CarnivalofSouls/CarnivalOfSouls.mp4",
    art: "https://archive.org/services/img/CarnivalofSouls",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Bloody Pit of Horror",
    year: 1965,
    dur: 4944,
    src: "https://archive.org/download/BloodyPitOfHorror/BloodyPitOfHorror.mp4",
    art: "https://archive.org/services/img/BloodyPitOfHorror",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Night of the Living Dead",
    year: 1968,
    dur: 5752.7,
    src: "https://archive.org/download/Night.Of.The.Living.Dead_1080p/NightOfTheLivingDead_1080p_512kb.mp4",
    desc: "The farmhouse siege that invented the modern zombie.",
    license: "Public domain",
    art: "https://archive.org/services/img/Night.Of.The.Living.Dead_1080p"
   },
   {
    title: "Grave of the Vampire",
    year: 1974,
    dur: 5380,
    src: "https://archive.org/download/Grave_of_the_Vampire_movie/Grave-of-the-Vampire_512kb.mp4",
    srcHi: "https://archive.org/download/Grave_of_the_Vampire_movie/Grave-of-the-Vampire.mp4",
    art: "https://archive.org/services/img/Grave_of_the_Vampire_movie",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "A Bucket of Blood",
    dur: 3928.2,
    src: "https://archive.org/download/ABucketofBlood/Bucket_1959_512kb.mp4",
    srcHi: "https://archive.org/download/ABucketofBlood/Bucket_1959.mp4",
    art: "https://archive.org/services/img/ABucketofBlood",
    desc: "",
    license: "via archive.org"
   }
  ]
 },
 {
  num: 5,
  id: "noir-alley",
  name: "Noir Alley",
  category: "Drama",
  tagline: "Shadows, cigarettes and bad decisions",
  art: "https://archive.org/services/img/Film_Noir",
  programs: [
   {
    title: "Detour",
    year: 1945,
    dur: 4058.3,
    src: "https://archive.org/download/Detour/Detour_512kb.mp4",
    srcHi: "https://archive.org/download/Detour/Detour.mp4",
    art: "https://archive.org/services/img/Detour",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Scarlet Street",
    year: 1945,
    dur: 6086.5,
    src: "https://archive.org/download/ScarletStreet/Scarlet_Street_512kb.mp4",
    srcHi: "https://archive.org/download/ScarletStreet/Scarlet_Street.mp4",
    art: "https://archive.org/services/img/ScarletStreet",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Strange Love of Martha Ivers",
    year: 1946,
    dur: 6949.2,
    src: "https://archive.org/download/Martha_Ivers_movie/Strange_Love_Martha_Ivers_512kb.mp4",
    srcHi: "https://archive.org/download/Martha_Ivers_movie/Strange_Love_Martha_Ivers.mp4",
    art: "https://archive.org/services/img/Martha_Ivers_movie",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "The Stranger",
    year: 1946,
    dur: 5472.9,
    src: "https://archive.org/download/TheStranger_0/The_Stranger_512kb.mp4",
    srcHi: "https://archive.org/download/TheStranger_0/The_Stranger.mp4",
    art: "https://archive.org/services/img/TheStranger_0",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Inner Sanctum",
    year: 1948,
    dur: 3720.6,
    src: "https://archive.org/download/Inner_Sanctum_movie/Inner_Sanctum_512kb.mp4",
    srcHi: "https://archive.org/download/Inner_Sanctum_movie/Inner_Sanctum.mp4",
    art: "https://archive.org/services/img/Inner_Sanctum_movie",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Impact",
    year: 1949,
    dur: 6578,
    src: "https://archive.org/download/impact/impact_512kb.mp4",
    srcHi: "https://archive.org/download/impact/impact.mp4",
    art: "https://archive.org/services/img/impact",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Quicksand",
    year: 1950,
    dur: 4742.4,
    src: "https://archive.org/download/Quicksand_clear/Quicksand.mp4",
    art: "https://archive.org/services/img/Quicksand_clear",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Jail Bait",
    year: 1954,
    dur: 4272.3,
    src: "https://archive.org/download/JailBait/JailBait_512kb.mp4",
    srcHi: "https://archive.org/download/JailBait/JailBait.mp4",
    art: "https://archive.org/services/img/JailBait",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Suddenly",
    year: 1954,
    dur: 4533.5,
    src: "https://archive.org/download/suddenly/suddenly_512kb.mp4",
    srcHi: "https://archive.org/download/suddenly/suddenly.mp4",
    art: "https://archive.org/services/img/suddenly",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Please Murder Me",
    year: 1956,
    dur: 4481.8,
    src: "https://archive.org/download/Please_Murder_Me_movie/Please_Murder_Me_512kb.mp4",
    srcHi: "https://archive.org/download/Please_Murder_Me_movie/Please_Murder_Me_x264.mp4",
    art: "https://archive.org/services/img/Please_Murder_Me_movie",
    desc: "",
    license: "via archive.org"
   }
  ]
 },
 {
  num: 6,
  id: "screwball-screen",
  name: "Screwball Screen",
  category: "Comedy",
  tagline: "Fast talk from the golden age",
  art: "https://archive.org/services/img/his_girl_friday",
  programs: [
   {
    title: "As You Like It",
    year: 1936,
    dur: 5783.6,
    src: "https://archive.org/download/AsYouLikeIt1936/AsYouLikeIt_512kb.mp4",
    art: "https://archive.org/services/img/AsYouLikeIt1936",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Charlie Chaplin Festival",
    year: 1938,
    dur: 4646.4,
    src: "https://archive.org/download/charlie_chaplin_film_fest/charlie_chaplin_film_fest_512kb.mp4",
    srcHi: "https://archive.org/download/charlie_chaplin_film_fest/charlie_chaplin_film_fest.mp4",
    art: "https://archive.org/services/img/charlie_chaplin_film_fest",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Tarzan and the Green Goddess",
    year: 1938,
    dur: 4045.6,
    src: "https://archive.org/download/tarzan_and_the_green_goddess/tarzan_and_the_green_goddess_512kb.mp4",
    srcHi: "https://archive.org/download/tarzan_and_the_green_goddess/tarzan_and_the_green_goddess.mp4",
    art: "https://archive.org/services/img/tarzan_and_the_green_goddess",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "The Flying Deuces",
    year: 1939,
    dur: 4077.6,
    src: "https://archive.org/download/TheFlyingDeuces/The_Flying_Deuces_512kb.mp4",
    srcHi: "https://archive.org/download/TheFlyingDeuces/The_Flying_Deuces.mp4",
    art: "https://archive.org/services/img/TheFlyingDeuces",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "His Girl Friday",
    year: 1940,
    dur: 5504.5,
    src: "https://archive.org/download/his_girl_friday/his_girl_friday_512kb.mp4",
    desc: "The fastest dialogue ever filmed.",
    license: "Public domain",
    art: "https://archive.org/services/img/his_girl_friday"
   },
   {
    title: "Meet John Doe",
    year: 1941,
    dur: 7371.2,
    src: "https://archive.org/download/meet_john_doe/meet_john_doe_512kb.mp4",
    srcHi: "https://archive.org/download/meet_john_doe/meet_john_doe.mp4",
    art: "https://archive.org/services/img/meet_john_doe",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "My Favorite Brunette",
    year: 1947,
    dur: 5212.5,
    src: "https://archive.org/download/my_favorite_brunette/my_favorite_brunette_512kb.mp4",
    srcHi: "https://archive.org/download/my_favorite_brunette/my_favorite_brunette.mp4",
    art: "https://archive.org/services/img/my_favorite_brunette",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Royal Wedding",
    year: 1951,
    dur: 5497.4,
    src: "https://archive.org/download/royal_wedding/royal_wedding_512kb.mp4",
    srcHi: "https://archive.org/download/royal_wedding/royal_wedding.mp4",
    art: "https://archive.org/services/img/royal_wedding",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "McLintock!",
    year: 1963,
    dur: 7607.2,
    src: "https://archive.org/download/mclintok_widescreen/McLintock_512kb.mp4",
    srcHi: "https://archive.org/download/mclintok_widescreen/McLintock.mp4",
    art: "https://archive.org/services/img/mclintok_widescreen",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "The Gun and the Pulpit",
    year: 1974,
    dur: 4432.1,
    src: "https://archive.org/download/cco_thegunandthepulpit/ccoPublicDomainThe_Gun_and_the_Pulpit_512kb.mp4",
    srcHi: "https://archive.org/download/cco_thegunandthepulpit/ccoPublicDomainThe_Gun_and_the_Pulpit.mp4",
    art: "https://archive.org/services/img/cco_thegunandthepulpit",
    desc: "",
    license: "via archive.org"
   }
  ]
 },
 {
  num: 7,
  id: "retro-vault",
  name: "Retro Vault",
  category: "Documentary",
  tagline: "Ephemeral films from the Prelinger vaults",
  art: "https://archive.org/services/img/DuckandC1951",
  programs: [
   {
    title: "About Bananas",
    year: 1935,
    dur: 664,
    src: "https://archive.org/download/AboutBan1935/AboutBan1935_512kb.mp4",
    srcHi: "https://archive.org/download/AboutBan1935/AboutBan1935.mp4",
    art: "https://archive.org/services/img/AboutBan1935",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Doctor in Industry (Part I)",
    year: 1946,
    dur: 1127.9,
    src: "https://archive.org/download/Doctorin1946/Doctorin1946_512kb.mp4",
    srcHi: "https://archive.org/download/Doctorin1946/Doctorin1946.mp4",
    art: "https://archive.org/services/img/Doctorin1946",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Joan Avoids a Cold",
    year: 1947,
    dur: 625.4,
    src: "https://archive.org/download/JoanAvoi1947/JoanAvoi1947_512kb.mp4",
    srcHi: "https://archive.org/download/JoanAvoi1947/JoanAvoi1947.mp4",
    art: "https://archive.org/services/img/JoanAvoi1947",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Care of the Skin",
    year: 1949,
    dur: 630.7,
    src: "https://archive.org/download/Careofth1949/Careofth1949_512kb.mp4",
    srcHi: "https://archive.org/download/Careofth1949/Careofth1949.mp4",
    art: "https://archive.org/services/img/Careofth1949",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Sleep for Health",
    year: 1950,
    dur: 644.3,
    src: "https://archive.org/download/Sleepfor1950/Sleepfor1950_512kb.mp4",
    srcHi: "https://archive.org/download/Sleepfor1950/Sleepfor1950.mp4",
    art: "https://archive.org/services/img/Sleepfor1950",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Duck and Cover",
    year: 1951,
    dur: 555.4,
    src: "https://archive.org/download/DuckandC1951/DuckandC1951_512kb.mp4",
    desc: "Bert the Turtle teaches Cold-War civil defense.",
    license: "Public domain · Prelinger",
    art: "https://archive.org/services/img/DuckandC1951"
   },
   {
    title: "The Home Economics Story",
    year: 1951,
    dur: 748.4,
    src: "https://archive.org/download/HomeEcon1951/HomeEcon1951_512kb.mp4",
    desc: "A gloriously earnest recruiting film.",
    license: "Public domain · Prelinger",
    art: "https://archive.org/services/img/HomeEcon1951"
   },
   {
    title: "Health: Your Posture",
    year: 1953,
    dur: 640.5,
    src: "https://archive.org/download/HealthYo1953/HealthYo1953_512kb.mp4",
    srcHi: "https://archive.org/download/HealthYo1953/HealthYo1953.mp4",
    art: "https://archive.org/services/img/HealthYo1953",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Eat for Health",
    year: 1954,
    dur: 624.5,
    src: "https://archive.org/download/EatforHe1954/EatforHe1954_512kb.mp4",
    srcHi: "https://archive.org/download/EatforHe1954/EatforHe1954.mp4",
    art: "https://archive.org/services/img/EatforHe1954",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "From the Ground Up",
    year: 1954,
    dur: 1145,
    src: "https://archive.org/download/FromtheG1954/FromtheG1954_512kb.mp4",
    srcHi: "https://archive.org/download/FromtheG1954/FromtheG1954.mp4",
    art: "https://archive.org/services/img/FromtheG1954",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Sniffles and Sneezes",
    year: 1955,
    dur: 583.2,
    src: "https://archive.org/download/Sniffles1955/Sniffles1955_512kb.mp4",
    srcHi: "https://archive.org/download/Sniffles1955/Sniffles1955.mp4",
    art: "https://archive.org/services/img/Sniffles1955",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Babies and Breadwinners (Part II)",
    dur: 596.8,
    src: "https://archive.org/download/babies_and_breadwinners_2/babies_and_breadwinners_2_512kb.mp4",
    srcHi: "https://archive.org/download/babies_and_breadwinners_2/babies_and_breadwinners_2.mp4",
    art: "https://archive.org/services/img/babies_and_breadwinners_2",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Breath-Takers, 2",
    dur: 987.4,
    src: "https://archive.org/download/breath_takers_2/breath_takers_2_512kb.mp4",
    srcHi: "https://archive.org/download/breath_takers_2/breath_takers_2.mp4",
    art: "https://archive.org/services/img/breath_takers_2",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Right to Health, A (Part I)",
    dur: 935.5,
    src: "https://archive.org/download/right_to_health_1/right_to_health_1_512kb.mp4",
    srcHi: "https://archive.org/download/right_to_health_1/right_to_health_1.mp4",
    art: "https://archive.org/services/img/right_to_health_1",
    desc: "",
    license: "via archive.org"
   }
  ]
 },
 {
  num: 8,
  id: "newsreel-nine",
  name: "Newsreel Nine",
  category: "News",
  tagline: "History as it happened, twice a week",
  art: "https://archive.org/services/img/universal_newsreels",
  programs: [
   {
    title: "Eve of Battle, 1944/06/06",
    year: 1944,
    dur: 1168.7,
    src: "https://archive.org/download/1944-06-06_Eve_of_Battle/1944-06-06_Eve_of_Battle_512kb.mp4",
    art: "https://archive.org/services/img/1944-06-06_Eve_of_Battle",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "RAF Sinks Tirpitz, 1944/11/22",
    year: 1944,
    dur: 448.9,
    src: "https://archive.org/download/1944-11-22_RAF_Sinks_Tirpitz/1944-11-22_RAF_Sinks_Tirpitz_512kb.mp4",
    art: "https://archive.org/services/img/1944-11-22_RAF_Sinks_Tirpitz",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Nazi Murder Mills, 1945/04/26",
    year: 1945,
    dur: 495.2,
    src: "https://archive.org/download/1945-04-26_Nazi_Murder_Mills/1945-04-26_Nazi_Murder_Mills_512kb.mp4",
    art: "https://archive.org/services/img/1945-04-26_Nazi_Murder_Mills",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Nazis Face War Crime Evidence, 1945/12/06",
    year: 1945,
    dur: 123.9,
    src: "https://archive.org/download/1945-12-06_Nazis_Face_War_Crime_Evidence/1945-12-06_Nazis_Face_War_Crime_Evidence_512kb.mp4",
    art: "https://archive.org/services/img/1945-12-06_Nazis_Face_War_Crime_Evidence",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "First Pictures Atomic Blast!, 1946/07/08",
    year: 1946,
    dur: 442.2,
    src: "https://archive.org/download/1946-07-08_First_Pictures_Atomic_Blast/1946-07-08_First_Pictures_Atomic_Blast_512kb.mp4",
    art: "https://archive.org/services/img/1946-07-08_First_Pictures_Atomic_Blast",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Jap Films of Hiroshima, 1946/08/05",
    year: 1946,
    dur: 433.4,
    src: "https://archive.org/download/1946-08-05_Jap_Films_of_Hiroshima/1946-08-05_Jap_Films_of_Hiroshima_512kb.mp4",
    art: "https://archive.org/services/img/1946-08-05_Jap_Films_of_Hiroshima",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Kansas, 1957/04/04",
    year: 1957,
    dur: 133.7,
    src: "https://archive.org/download/1957-04-04_Kansas/1957-04-04_Kansas_512kb.mp4",
    art: "https://archive.org/services/img/1957-04-04_Kansas",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "First U.S. Satellite Launched! 1958/02/03",
    year: 1958,
    dur: 169.5,
    src: "https://archive.org/download/1958-02-03_First_US_Satellite_Launched/1958-02-03_First_US_Satellite_Launched_512kb.mp4",
    art: "https://archive.org/services/img/1958-02-03_First_US_Satellite_Launched",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "The Cuban Crisis, 1962/10/25",
    year: 1962,
    dur: 360.4,
    src: "https://archive.org/download/1962-10-25_The_Cuban_Crisis/1962-10-25_The_Cuban_Crisis_512kb.mp4",
    art: "https://archive.org/services/img/1962-10-25_The_Cuban_Crisis",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "The Red Threat. President Orders Cuban Blockade, 1962/10/22",
    year: 1962,
    dur: 188.6,
    src: "https://archive.org/download/1962-10-22_The_Red_Threat/1962-10-22_The_Red_Threat_512kb.mp4",
    art: "https://archive.org/services/img/1962-10-22_The_Red_Threat",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Fashions, 1964/10/26",
    year: 1964,
    dur: 127.6,
    src: "https://archive.org/download/1964-10-26_Fashions/1964-10-26_Fashions_512kb.mp4",
    art: "https://archive.org/services/img/1964-10-26_Fashions",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Peace March. Thousands Oppose Vietnam War, 1967/04/18",
    year: 1967,
    dur: 170.4,
    src: "https://archive.org/download/1967-04-18_Peace_March/1967-04-18_Peace_March_512kb.mp4",
    art: "https://archive.org/services/img/1967-04-18_Peace_March",
    desc: "",
    license: "via archive.org"
   }
  ]
 },
 {
  num: 9,
  id: "tube-classics",
  name: "Tube Classics",
  category: "Entertainment",
  tagline: "The golden age of the small screen",
  art: "https://archive.org/services/img/classic_tv",
  programs: [
   {
    title: "The Lone Ranger TV Show",
    year: 1949,
    dur: 1301.8,
    src: "https://archive.org/download/theloneranger_201705/s01e13_finderskeepers.mp4",
    srcHi: "https://archive.org/download/theloneranger_201705/s01e04_TheLegionofOldTimers.mp4",
    art: "https://archive.org/services/img/theloneranger_201705",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Dragnet",
    year: 1951,
    dur: 1571.4,
    src: "https://archive.org/download/Dragnet1951/Dragnet/Season%203/Dragnet%20(1951)%20-%20S03E24%20-%20The%20Big%20Children.ia.mp4",
    srcHi: "https://archive.org/download/Dragnet1951/Dragnet/Season%207/Dragnet%20(1951)%20-%20S07E28%20-%20The%20Big%20War.mp4",
    art: "https://archive.org/services/img/Dragnet1951",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Beverly Hillbillies Ep01 The Clampetts Strike Oil",
    dur: 1492.3,
    src: "https://archive.org/download/Beverly_Hillbillies_Ep01_The_Clampetts_Strike_Oil/BH01_The_Clampetts_Strike_Oil_512kb.mp4",
    art: "https://archive.org/services/img/Beverly_Hillbillies_Ep01_The_Clampetts_Strike_Oil",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Bonanza - Bitter Water",
    dur: 2964.2,
    src: "https://archive.org/download/Bonanza-BitterWater/Bonanza_Bitter_Water_S01-E29_512kb.mp4",
    art: "https://archive.org/services/img/Bonanza-BitterWater",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Bonanza - Day Of Reckoning",
    dur: 2965.8,
    src: "https://archive.org/download/Bonanza_-_Day_Of_Reckoning/Bonanza_-_Day_Of_Reckoning_512kb.mp4",
    art: "https://archive.org/services/img/Bonanza_-_Day_Of_Reckoning",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Bonanza - Silent Thunder",
    dur: 2960.5,
    src: "https://archive.org/download/Bonanza_-_Silent_Thunder/Bonanza_-_Silent_Thunder_512kb.mp4",
    art: "https://archive.org/services/img/Bonanza_-_Silent_Thunder",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Bonanza - The Fear Merchants",
    dur: 2939.4,
    src: "https://archive.org/download/Bonanza-TheFearMerchants/Bonanza_-_The_Fear_Merchants_S01-E20_512kb.mp4",
    art: "https://archive.org/services/img/Bonanza-TheFearMerchants",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Bonanza - The Savage",
    dur: 2964,
    src: "https://archive.org/download/Bonanza_-_The_Savage/Bonanza_-_The_Savage_512kb.mp4",
    art: "https://archive.org/services/img/Bonanza_-_The_Savage",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Bonanza - The Spitfire",
    dur: 2963.6,
    src: "https://archive.org/download/Bonanza_-_The_Spitfire/Bonanza_-_The_Spitfire_512kb.mp4",
    art: "https://archive.org/services/img/Bonanza_-_The_Spitfire",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Bonanza - The Trail Gang",
    dur: 2957.3,
    src: "https://archive.org/download/Bonanza_-_The_Trail_Gang/Bonanza_-_The_Trail_Gang_512kb.mp4",
    art: "https://archive.org/services/img/Bonanza_-_The_Trail_Gang",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Bonanza public domain episodes",
    dur: 2892.7,
    src: "https://archive.org/download/Bonanza_pd/BonanzaS02e07.mp4",
    srcHi: "https://archive.org/download/Bonanza_pd/BonanzaS02e10.mp4",
    art: "https://archive.org/services/img/Bonanza_pd",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Lucy meets John Wayne",
    dur: 1521.1,
    src: "https://archive.org/download/TLS_Lucy_Meets_John_Wayne/TLS_Lucy_Meets_John_Wayne_512kb.mp4",
    art: "https://archive.org/services/img/TLS_Lucy_Meets_John_Wayne",
    desc: "",
    license: "via archive.org"
   }
  ]
 },
 {
  num: 10,
  id: "silent-palace",
  name: "Silent Palace",
  category: "Film",
  tagline: "No talking. Piano optional.",
  art: "https://archive.org/services/img/silent_films",
  programs: [
   {
    title: "Charlie Chaplin's \"A Burlesque On Carmen\"",
    year: 1915,
    dur: 2622.5,
    src: "https://archive.org/download/CC_1915_12_18_ABurlesqueOnCarmen/CC_1915_12_18_ABurlesqueOnCarmen_512kb.mp4",
    art: "https://archive.org/services/img/CC_1915_12_18_ABurlesqueOnCarmen",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "20,000 Leagues Under the Sea",
    year: 1916,
    dur: 5922.3,
    src: "https://archive.org/download/20000LeaguesUndertheSea/20000_Leagues_Under_the_Sea_512kb.mp4",
    art: "https://archive.org/services/img/20000LeaguesUndertheSea",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Charlie Chaplin's \"The Count\"",
    year: 1916,
    dur: 1211,
    src: "https://archive.org/download/CC_1916_09_04_TheCount/CC_1916_09_04_TheCount_512kb.mp4",
    art: "https://archive.org/services/img/CC_1916_09_04_TheCount",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Charlie Chaplin's \"The Floorwalker\"",
    year: 1916,
    dur: 1169.8,
    src: "https://archive.org/download/CC_1916_05_15_TheFloorwalker/CC_1916_05_15_TheFloorwalker_512kb.mp4",
    art: "https://archive.org/services/img/CC_1916_05_15_TheFloorwalker",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Charlie Chaplin's \"The Rink\"",
    year: 1916,
    dur: 1169.8,
    src: "https://archive.org/download/CC_1916_12_04_TheRink/CC_1916_12_04_TheRink_512kb.mp4",
    art: "https://archive.org/services/img/CC_1916_12_04_TheRink",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Das Kabinett des Doktor Caligari ( The Cabinet of Dr. Caligari )",
    year: 1919,
    dur: 3061.5,
    src: "https://archive.org/download/DasKabinettdesDoktorCaligariTheCabinetofDrCaligari/The_Cabinet_of_Dr._Caligari_512kb.mp4",
    art: "https://archive.org/services/img/DasKabinettdesDoktorCaligariTheCabinetofDrCaligari",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "West of Hot Dog",
    year: 1924,
    dur: 1834.7,
    src: "https://archive.org/download/westofhotdog/WestOfHotDog_512kb.mp4",
    srcHi: "https://archive.org/download/westofhotdog/WestOfHotDog.mp4",
    art: "https://archive.org/services/img/westofhotdog",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Bronenosets Potyomkin (Battleship Potemkin)",
    year: 1925,
    dur: 4381.4,
    src: "https://archive.org/download/BattleshipPotemkin/Battleship_Potemkin_512kb.mp4",
    art: "https://archive.org/services/img/BattleshipPotemkin",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "The Phantom of the Opera",
    year: 1925,
    dur: 6388.9,
    src: "https://archive.org/download/ThePhantomoftheOpera/Phantom_of_the_Opera_512kb.mp4",
    art: "https://archive.org/services/img/ThePhantomoftheOpera",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Que Viva Mexico",
    year: 1931,
    dur: 5081.6,
    src: "https://archive.org/download/QuevivaMexico/Que.viva.Mexico_512kb.mp4",
    art: "https://archive.org/services/img/QuevivaMexico",
    desc: "",
    license: "via archive.org"
   }
  ]
 },
 {
  num: 11,
  id: "trailer-park",
  name: "Trailer Park",
  category: "Entertainment",
  tagline: "Coming attractions, forever",
  art: "https://archive.org/services/img/movie_trailers",
  programs: [
   {
    title: "BANANAS trailer",
    dur: 197.4,
    src: "https://archive.org/download/BananasTrailer_733/BananasTrailer.mp4",
    art: "https://archive.org/services/img/BananasTrailer_733",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "FANTASTIC PLANET trailer",
    dur: 135.1,
    src: "https://archive.org/download/FantasticPlanetTrailer/FantasticPlanetTrailer.mp4",
    art: "https://archive.org/services/img/FantasticPlanetTrailer",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Night of the living dead Trailer",
    dur: 95,
    src: "https://archive.org/download/NightOfTheLivingDeadTrailer/NightLivingDeadTrailer_512kb.mp4",
    srcHi: "https://archive.org/download/NightOfTheLivingDeadTrailer/NightLivingDeadTrailer.mp4",
    art: "https://archive.org/services/img/NightOfTheLivingDeadTrailer",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "REVENGE OF THE CREATURE trailer",
    dur: 150.6,
    src: "https://archive.org/download/RevengeOfTheCreatureTrailer/RevengeOfTheCreatureTrailer.mp4",
    art: "https://archive.org/services/img/RevengeOfTheCreatureTrailer",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Sita Sings the Blues Trailer 2008 - 640x360",
    dur: 101,
    src: "https://archive.org/download/SitaSingsTheBluesTrailer2008-640x360/SitaTrailer2008H264_512kb.mp4",
    art: "https://archive.org/services/img/SitaSingsTheBluesTrailer2008-640x360",
    desc: "",
    license: "via archive.org"
   }
  ]
 },
 {
  num: 12,
  id: "moon-tv",
  name: "Moon TV",
  category: "Science & Tech",
  tagline: "One small step, on a loop",
  art: "https://archive.org/services/img/youtube-S9HdPi9Ikhk",
  programs: [
   {
    title: "Apollo 11 Moonwalk (Restored)",
    year: 1969,
    dur: 10950,
    src: "https://archive.org/download/youtube-S9HdPi9Ikhk/S9HdPi9Ikhk.mp4",
    desc: "NASA's restored original EVA television.",
    license: "Public domain · NASA",
    art: "https://archive.org/services/img/youtube-S9HdPi9Ikhk"
   },
   {
    title: "NASA SCI Files - Reproduction, Migration and Basic Needs",
    year: 2005,
    dur: 793.8,
    src: "https://archive.org/download/NasaSciFiles-ReproductionMigrationAndBasicNeeds/NASASF-ReproductionMigrationAndBasicNeeds_512kb.mp4",
    srcHi: "https://archive.org/download/NasaSciFiles-ReproductionMigrationAndBasicNeeds/NASASF-ReproductionMigrationAndBasicNeeds.mp4",
    art: "https://archive.org/services/img/NasaSciFiles-ReproductionMigrationAndBasicNeeds",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "NASA 360 Episode 1",
    year: 2008,
    dur: 1469.2,
    src: "https://archive.org/download/NASA_360_program1_HD/NASA_360_program1_HD_512kb.mp4",
    art: "https://archive.org/services/img/NASA_360_program1_HD",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Nasa eClips Video",
    year: 2009,
    dur: 273.5,
    src: "https://archive.org/download/nasa_eclips_022709/RW_LRO_Resources_oc_512kb.mp4",
    srcHi: "https://archive.org/download/nasa_eclips_022709/OW_THE_SUN_ff_oc.mp4",
    art: "https://archive.org/services/img/nasa_eclips_022709",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Nasa eClips Video Series",
    year: 2009,
    dur: 301,
    src: "https://archive.org/download/nasa_eclips_022309/LP_Ares_1X_OC_512kb.mp4",
    srcHi: "https://archive.org/download/nasa_eclips_022309/OW_ARES_oc_512kb.mp4",
    art: "https://archive.org/services/img/nasa_eclips_022309",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Our World: Arecibo - The Largest Radio Telescope on Earth",
    year: 2009,
    dur: 248.8,
    src: "https://archive.org/download/nasa_eclips_081009/OW43_RockCycle_512kb.mp4",
    srcHi: "https://archive.org/download/nasa_eclips_081009/OW42_Subrip_512kb.mp4",
    art: "https://archive.org/services/img/nasa_eclips_081009",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Ourworld: Fluid Shift and Our World: Investigating Mars with the Phoen",
    year: 2009,
    dur: 292.9,
    src: "https://archive.org/download/nasa_eclips_052609/OW31InvestigatingMars_512kb.mp4",
    srcHi: "https://archive.org/download/nasa_eclips_052609/OW46FluidShift.ia.mp4",
    art: "https://archive.org/services/img/nasa_eclips_052609",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "Space Operations",
    year: 2009,
    dur: 332.6,
    src: "https://archive.org/download/nasa_eclips_110209/RW42_SubRip_512kb.mp4",
    srcHi: "https://archive.org/download/nasa_eclips_110209/NASA_Launchpad_Methane_on_Mars.ia.mp4",
    art: "https://archive.org/services/img/nasa_eclips_110209",
    desc: "",
    license: "via archive.org"
   },
   {
    title: "NASA eClips",
    dur: 268.2,
    src: "https://archive.org/download/nasa_eclips_01162009/RW_ISRU.mp4",
    srcHi: "https://archive.org/download/nasa_eclips_01162009/NASA_360_6.mp4",
    art: "https://archive.org/services/img/nasa_eclips_01162009",
    desc: "",
    license: "via archive.org"
   }
  ]
 }
];

/* EPG category rail — vocabulary from the 2007 client's catalog */
const EPG_CATEGORIES = [
 {
  id: "explore",
  label: "Explore",
  icon: "◉"
 },
 {
  id: "my",
  label: "My Channels",
  icon: "★"
 },
 {
  id: "Cartoons & Animation",
  label: "Cartoons & Animation",
  icon: "▸"
 },
 {
  id: "Film",
  label: "Film",
  icon: "▸"
 },
 {
  id: "Kids",
  label: "Kids",
  icon: "▸"
 },
 {
  id: "Cult",
  label: "Cult",
  icon: "▸"
 },
 {
  id: "Drama",
  label: "Drama",
  icon: "▸"
 },
 {
  id: "Comedy",
  label: "Comedy",
  icon: "▸"
 },
 {
  id: "Documentary",
  label: "Documentary",
  icon: "▸"
 },
 {
  id: "News",
  label: "News",
  icon: "▸"
 },
 {
  id: "Entertainment",
  label: "Entertainment",
  icon: "▸"
 },
 {
  id: "Science & Tech",
  label: "Science & Tech",
  icon: "▸"
 }
];

/* Broadcast epoch: 16 Jan 2007, the day The Venice Project became "Joost". */
const BROADCAST_EPOCH = Date.UTC(2007, 0, 16, 0, 0, 0);
